require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Metrics/LineLength:
  Max: 100
  Exclude:
    - config/**
    - config/**/*

AllCops:
  Exclude:
    - 'node_modules/**'
    - 'node_modules/**/*'
