require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/**'
    - 'config/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**'
    - 'spec/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**'
    - 'spec/views/**'
    - 'spec/views/**/*'

RSpec/MultipleExpectations:
  Max: 2

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/ExampleLength:
  Max: 10

AllCops:
  Exclude:
    - 'node_modules/**'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
