name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
        - 6379:6379

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7.1

    - name: Set up Node 13.2.0
      uses: actions/setup-node@v1
      with:
        node-version: 13.2.0

    - name: Install PostgreSQL 11 client
      run: sudo apt-get -yqq install libpq-dev

    - name: Set Environment Variables
      uses: allenevans/set-env@v1.0.0
      with:
        PGHOST: localhost
        PGUSER: postgres
        REDIS_URL: redis://localhost:6379
        RAILS_ENV: test

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        yarn install

    - name: Setup DB
      run: bin/rails db:create db:migrate

    - name: Test/Build App
      run: bin/build
